---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  product_name: chef
  product_version: 14

platforms:
  - name: ubuntu-16.04
    driver:
      box: xenial64-lxc
      provider: lxc
    run_list:
      - recipe[apt]

suites:
  - name: client
    run_list:
      - recipe[munin::client]
  - name: server
    run_list:
      - recipe[munin::server]
  - name: server_apache
    run_list:
      - recipe[munin::server_apache]
  - name: server_nginx
    run_list:
      - recipe[munin::server_nginx]
